### ISSUE TITLE
[Feature Request] visualization

### ISSUE THREAD

**Issue by ishakbhatt-h3d** [alesof/ROS2-VSC-Toolkit#2]
This tool has been extremely useful since I heard about it! Are there plans to expand it to include other functionalities such as viewing the graphical output of certain topics? For example, if there is an occupancy map being published and I want to remote into it and look at it, I could maybe look at the visualization of that topic. It's definitely would not be trivial to implement as it's already hard enough to do X forwarding on a local machine and open rviz, but curious if that enhancement is in the pipeline

**Comment by alesof** [comment]
Hi @ishakbhatt-h3d!

Thanks for sharing this idea. This is not currently in pipeline, but it's definitly something I'll consider for future updates. Do you think this would be helpful during development instead of relying on external tools such as [rviz ](https://github.com/ros2/rviz) or [foxglove](https://foxglove.dev/)?

If you or anyone else is interested in helping developing this feature I'd be happy to integrate it.
